---
- name: Create ingress yaml dir
  file: name={{ yaml_dir }}/ingress state=directory

- name: Get ingress yaml files
  template: src={{ item }} dest={{ yaml_dir }}/ingress/{{ item }}
  with_items:
  - ingress.yaml
  - ingress-service.yaml

- name: Create ingress
  raw: kubectl get po -n ingress-nginx|grep ingress || kubectl create -f {{ yaml_dir }}/ingress/ingress.yaml

- name: Create ingress service1
  raw: kubectl get svc -n ingress-nginx|grep service1 || kubectl create -f {{ yaml_dir }}/ingress/ingress-service.yaml



