- name: Install cloud init
  apt: name=cloud-init state=latest update_cache=yes 
- name: Set hostname
  command: hostnamectl set-hostname {{ host_name }}

- name: Update cloud.cfg
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^preserve_hostname:"
    line: "preserve_hostname: true"

- name: Install socat for Ubuntu server
  apt: name={{ item }} state=latest
  with_items:
  - socat
     
- name: Clear iptables rules
  command: iptables -P FORWARD ACCEPT

- name: Disable swap temporary
  command: swapoff -a

- name: Disable swap in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: Modify sysctl config
  template: src=k8s-sysctl.conf.j2 dest=/etc/sysctl.d/k8s-sysctl.conf

- name: Modify host file
  template: src=hosts dest=/etc/hosts

- name: Enable br_netfilter module
  modprobe: name=br_netfilter state=present
  ignore_errors: true
  
- name: Enable sysctl setup
  raw: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"
  ignore_errors: true

- name: Install basic pkg
  apt: name={{ item }} update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: Add docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable 

- name: Install Docker
  apt:
    name: docker-ce=5:{{ docker_version }}~3-0~ubuntu-bionic
    update_cache: yes

- name: Restart Docker 
  service: name=docker state=restarted

- name: Add kubernetes apt-key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes source list
  shell: >
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

- name: Install kubernetes tools for Ubuntu server
  apt: name={{ item }} update_cache=yes
  with_items:
  - kubelet={{ kubelet_version }}
  - kubectl={{ kubectl_version }}
  - kubeadm={{ kubeadm_version }}

