- name: Create kubectl config folder
  file: name=/root/.kube state=directory

- name: Get joining command from init master 
  copy: src={{ kube_cert_dir }}/master_join dest=/root/.kube/master_join

- name: Join current node into the cluster
  shell: eval "$(cat /root/.kube/master_join)"

- name: Copy kubectl config
  shell: cp {{ kube_config_dir }}/admin.conf /root/.kube/config




